# Generated by Django 5.1.4 on 2025-01-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qtde_total',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
